import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        serif: ["Bodoni Moda", "Georgia", "serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      colors: {
        "on-surface": "#1f1b16",
        "secondary-container": "#b9f079",
        outline: "#8c7164",
        "primary-container": "#f97316",
        "primary-fixed": "#ffdbca",
        "surface-tint": "#9d4300",
        tertiary: "#735c00",
        "on-primary-container": "#582200",
        "on-error": "#ffffff",
        "on-background": "#1f1b16",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#faefe7",
        background: "#fff8f4",
        "surface-container": "#f7ece4",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#eec200",
        "on-secondary-fixed-variant": "#2e4f00",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#341100",
        "tertiary-container": "#cea700",
        "secondary-fixed-dim": "#a0d663",
        "error-container": "#ffdad6",
        "on-surface-variant": "#584237",
        "surface-dim": "#e3d8d1",
        "inverse-surface": "#352f2b",
        "secondary-fixed": "#bbf37c",
        "surface-variant": "#ebe1d9",
        secondary: "#3e6a00",
        "surface-container-highest": "#ebe1d9",
        "on-secondary-fixed": "#0f2000",
        "on-tertiary-fixed": "#231b00",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffe083",
        "on-error-container": "#93000a",
        "surface-container-low": "#fdf2ea",
        "surface-container-high": "#f1e6df",
        "inverse-primary": "#ffb690",
        "primary-fixed-dim": "#ffb690",
        "surface-bright": "#fff8f4",
        "on-secondary-container": "#416e00",
        "outline-variant": "#e0c0b1",
        "on-tertiary-container": "#4e3e00",
        surface: "#fff8f4",
        "on-tertiary-fixed-variant": "#574500",
        "surface-container-lowest": "#ffffff",
        primary: "#9d4300",
        "on-primary-fixed-variant": "#783200",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
      },
      boxShadow: {
        soft: "0 4px 20px rgba(15, 23, 42, 0.05)",
      },
    },
  },
  plugins: [],
};

export default config;
