import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "currency-display": ["Hanken Grotesk"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.01em" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "currency-display": ["36px", { lineHeight: "44px", fontWeight: "700" }],
      },
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#584237",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#8c7164",
        "outline-variant": "#e0c0b1",
        "surface-tint": "#9d4300",
        primary: "#9d4300",
        "on-primary": "#ffffff",
        "primary-container": "#f97316",
        "on-primary-container": "#582200",
        "inverse-primary": "#ffb690",
        secondary: "#565e74",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "secondary-fixed-dim": "#bec6e0",
        tertiary: "#006e2f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00b251",
        "on-tertiary-container": "#003b16",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "income-green": "#00b251",
        "expense-red": "#ba1a1a",
        border: "#e0c0b1",
        input: "#e0c0b1",
        ring: "#9d4300",
        card: "#ffffff",
        "card-foreground": "#0b1c30",
        muted: "#e5eeff",
        "muted-foreground": "#565e74",
        accent: "#f97316",
        "accent-foreground": "#ffffff",
        destructive: "#ba1a1a",
        "destructive-foreground": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        gutter: "16px",
      },
      boxShadow: {
        soft: "0 4px 20px rgba(15, 23, 42, 0.05)",
        fab: "0 4px 20px rgba(249, 115, 22, 0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
